version: '3'

services:
  webserver:
    image: nginx:latest
    volumes:
      - ./resources/nginx55/default.conf:/etc/nginx/conf.d/default.conf
      - ./resources/code/connection.ini:/var/www/connection.ini
      - ./resources/code/aimsis:/var/www/aimsis
      - ./resources/code/api-php:/var/www/api-php
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "54:81"
      - "443:443"
    depends_on:
      - php55fpm 
  php55fpm:
    build:
      context: .
      dockerfile: php55.Dockerfile
    volumes:
      - ./resources/code/connection.ini:/var/www/connection.ini
      - ./resources/code/aimsis:/var/www/aimsis
      - ./resources/code/api-php:/var/www/api-php
      - ./resources/phpini55/php.ini:/usr/local/etc/php/php.ini
    restart: always
    depends_on:
      - database
  database:
    image: mysql:5.5
    restart: always
    environment:
      MYSQL_DATABASE: mydb
      MYSQL_USER: root
      MYSQL_PASSWORD: aimsis
      MYSQL_ROOT_PASSWORD: aimsis
    ports:
      - 33062:3306
    expose:
      - 33062
    volumes:
      - ./resources/mysql55:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_PORT: 3306
      PMA_HOST: database
      PMA_USER: root
      PMA_PASSWORD: aimsis
    ports:
    - "8004:80"
    restart: always
    depends_on:
    - database