version: '3'

services:
  webserver:
    image: nginx:latest
    volumes:
      - ./resources/nginx55/default.conf:/etc/nginx/conf.d/default.conf
      - ./resources/code:/var/www
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - php55fpm 
  php55fpm:
    build:
      context: ./resources/php55fpm
      dockerfile: Dockerfile
    volumes:
      - ./resources/code:/var/www
      - ./resources/phpini55/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - database
  database:
    image: mysql:5.5
    restart: always
    environment:
      MYSQL_DATABASE: mydb
      MYSQL_USER: root
      MYSQL_PASSWORD: dimas
      MYSQL_ROOT_PASSWORD: dimas
    ports:
      - 3306:3306
    expose:
      - 3306
    volumes:
      - ./resources/mysql55:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_PORT: 3306
      PMA_HOST: database
      PMA_USER: root
      PMA_PASSWORD: dimas
    ports:
    - "8004:80"
    restart: always
    depends_on:
    - database